### ISSUE TITLE
edit vendor attribute

### ISSUE THREAD

**Issue by androidsx2** [BitBagCommerce/OpenMarketplace#143]
hi!
a) login as vendor
b) create a new attribute
c) apply the new attribute in a product listing
d) save listing --> system error

after that, there is no way to **edit a vendor attribute** (eg, https://demo.open-marketplace.io/en_US/account/vendor/product-attributes/12664/update --> 500 Internal Server Error".)

**Comment by DominikWolos** [comment]
Hi @androidsx2, 
I believe that I've already fixed that issue, but we haven't made another release yet.
Were you facing this on latest master or on latest release?

**Comment by androidsx2** [comment]
release!
if you click on above link you will get 500

**Comment by DominikWolos** [comment]
Yes, we are aware of it and as I've mentioned - this issue is already fixed on latest master.
I am in no way the decisive person on this matter, but I suppose new release will be made in the nearest future but I won't happen until 2024. Optimistically I would say January but there are some changes we need to test internally that may delay the release.

If you need this change you can either cherry pick commit [a8962e5](https://github.com/BitBagCommerce/OpenMarketplace/pull/132/commits/a8962e56a3c9111904b47163caa442efc1639064), or fork repository and apply changes from existing(yet) [branch](https://github.com/BitBagCommerce/OpenMarketplace/tree/hotfix/MUL-298-build-fails-deprecated-merge-method) covering some issues with build we've faced.

I am closing this thread for now, please re-open if something still needs our awareness or there are any further questions.

**Comment by androidsx2** [comment]
:)
