### ISSUE TITLE
OpenMarketPlace creating database error

### ISSUE THREAD

**Issue by quiloos39** [BitBagCommerce/OpenMarketplace#32]
System information
PHP: 8.1.7
Composer: 2.4.1

I am getting the following error.

`PHP Fatal error:  Type of BitBag\OpenMarketplace\Form\ProductListing\ProductPriceType::$dataClass must be string (as in class Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType) in /root/project/src/Form/ProductListing/ProductPriceType.php on line 27`

**Comment by MacBalc** [comment]
Hello, were You using newest version of open-marketplace? If so, could You provide some steps that lead to this error occurence?

**Comment by SardonnayK** [comment]
I ran into the same issue when I was following the installation docs. 
The problem is in the file `ProductPriceType.php`, we need to explicitly set the datatype for 
the `$dataClass` variable to `string` on `line 31`.

I was using the tag `V1.0.4` when I ran into this problem. Hopefully this is helpful.

**Comment by MacBalc** [comment]
Ah, yes, at the new release it won't be a problem anymore. Thank You for feedback!
